const s3Config = {
  bucketName: process.env.S3_BUCKET_NAME || "tu-bucket",
  region: process.env.AWS_REGION || "us-east-2",
  accessKeyId: process.env.AWS_ACCESS_KEY_ID || "TU",
  secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || "TU",
  allowedFormats: [
    "jpg",
    "jpeg",
    "png",
    "gif",
    "webp",
    "avif",
    "svg",
    "bmp",
    "tiff",
    "ico",
    "pdf",
    "docx",
    "xlsx",
    "pptx",
    "txt",
    "csv",
    "mp4",
    "avi",
    "mov",
    "wmv",
    "flv",
    "mkv",
    "webm",
    "mp3",
    "wav",
    "ogg",
    "flac",
  ],
  maxFileSizeMB: 100,
  defaultFolder: "user-profiles",
  signedUrlExpiration: 3600, // 1 hora para URLs firmadas
};

export const s3ConfigGirls = {
  bucketName: process.env.S3_BUCKET_NAME || "tu-bucket",
  region: process.env.AWS_REGION || "us-east-2",
  accessKeyId: process.env.AWS_ACCESS_KEY_ID || "TU",
  secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || "TU",
  allowedFormats: [
    "jpg",
    "jpeg",
    "png",
    "gif",
    "webp",
    "avif",
    "svg",
    "bmp",
    "tiff",
    "ico",
    "pdf",
    "docx",
    "xlsx",
    "pptx",
    "txt",
    "csv",
    "mp4",
    "avi",
    "mov",
    "wmv",
    "flv",
    "mkv",
    "webm",
    "mp3",
    "wav",
    "ogg",
    "flac",
  ],
  maxFileSizeMB: 100,
  defaultFolder: "goodnes-girls",
  signedUrlExpiration: 3600, // 1 hora para URLs firmadas
};

export default s3Config;
